<?php
/**
 * Legacy redirects (301 / 410), the custom 404 page and a 404 log.
 *
 * Old urban.org.in URLs that the canonical-URL map (redirects.php) does not
 * cover are resolved from redirects-extra.php (generated by
 * _scripts/seo/build_redirects.py): exact 301s, exact 410s (Gone) and ordered
 * patterns. Anything still unmatched gets a real 404 page in the site's design -
 * never a redirect to the homepage, which search engines treat as a soft 404.
 *
 *  - 301: the content moved / has a successor.
 *  - 410: removed on purpose, no successor (lorem-ipsum test pages, expired jobs,
 *    plugin demo pages, author archives, hacked-in spam, deleted uploads). 410
 *    makes crawlers drop the URL faster than 404.
 *  - 404 page: friendly, noindex, "did you mean" suggestions, popular pages.
 *  - Tools > 404 log (wp-admin): the URLs visitors and crawlers could not find,
 *    most-hit first - the to-do list for new redirects.
 */

defined( 'ABSPATH' ) || exit;

/* ------------------------------------------------------------ redirects */

function ucan_legacy_rules() {
	static $r = null;
	if ( null === $r ) {
		$f = dirname( __DIR__ ) . '/redirects-extra.php';
		$r = is_file( $f ) ? include $f : array();
		$r = array_merge( array( 'exact' => array(), 'gone' => array(), 'patterns' => array() ), (array) $r );
	}
	return $r;
}

/** @return array|null array( 301, '/target' ) | array( 410, null ) | null (no rule) */
function ucan_resolve_legacy( $key, $rules, $depth = 0 ) {
	$key = strtolower( trim( (string) $key, '/' ) );
	if ( '' === $key ) {
		return null;
	}
	if ( isset( $rules['exact'][ $key ] ) ) {
		return array( 301, $rules['exact'][ $key ] );
	}
	if ( isset( $rules['gone'][ $key ] ) ) {
		return array( 410, null );
	}
	if ( $depth < 2 && preg_match( '#^(.+)/page/\d+$#', $key, $m ) ) { // old paginated archives
		return ucan_resolve_legacy( $m[1], $rules, $depth + 1 );
	}
	foreach ( $rules['patterns'] as $p ) {
		if ( preg_match( $p[0], $key ) ) {
			return null === $p[1] ? array( 410, null ) : array( 301, $p[1] );
		}
	}
	return null;
}

/** Redirect (or 410) if a legacy rule matches; otherwise return and let the 404 page handle it. */
function ucan_legacy_redirect( $key, $home ) {
	$r = ucan_resolve_legacy( $key, ucan_legacy_rules() );
	if ( ! $r ) {
		return;
	}
	if ( 410 === $r[0] ) {
		ucan_serve_error_page( 410 );
	}
	wp_safe_redirect( $home . $r[1], 301 ); // query strings on old URLs are junk (tracking, plugin logins): dropped on purpose
	exit;
}

/* ------------------------------------------------------- 404 / 410 page */

function ucan_fill_placeholders( $html ) {
	$home = ucan_public_origin( untrailingslashit( home_url() ) );
	return str_replace(
		array( '%%UCAN_THEME%%', '%%UCAN_HOME%%', '%%UCAN_API%%' ),
		array( ucan_on_origin( get_template_directory_uri(), $home ), $home, ucan_on_origin( esc_url_raw( rest_url( 'ucan/v1/subscribe' ) ), $home ) ),
		$html
	);
}

/** Up to $limit likely pages for a mistyped/old path, by slug similarity + shared words. */
function ucan_suggest_pages( $path, $limit = 3 ) {
	$f      = dirname( __DIR__ ) . '/inc/page-titles.php';
	$titles = is_file( $f ) ? include $f : array();
	$seg    = strtolower( basename( trim( (string) $path, '/' ) ) );
	$seg    = trim( (string) preg_replace( '/[^a-z0-9]+/', '-', (string) preg_replace( '/\.[a-z0-9]+$/', '', $seg ) ), '-' );
	if ( strlen( $seg ) < 3 ) {
		return array();
	}
	$words  = array_values( array_filter( explode( '-', $seg ), function ( $w ) {
		return strlen( $w ) > 3;
	} ) );
	$scores = array();
	foreach ( $titles as $slug => $title ) {
		similar_text( $seg, $slug, $pct );
		$hits = 0;
		foreach ( $words as $w ) {
			if ( false !== strpos( $slug, $w ) ) {
				++$hits;
			}
		}
		$scores[ $slug ] = $pct + ( $words ? 25 * $hits / count( $words ) : 0 );
	}
	arsort( $scores );
	$out = array();
	foreach ( $scores as $slug => $score ) {
		if ( $score < 60 || count( $out ) >= $limit ) {
			break;
		}
		$out[ $slug ] = $titles[ $slug ];
	}
	return $out;
}

/**
 * The error page = the site's own header/menu/footer (taken from an existing page, so it can
 * never drift from the rest of the site) + inc/404-fragment.html (head extras and <main>).
 */
function ucan_error_template() {
	$frag  = dirname( __DIR__ ) . '/inc/404-fragment.html';
	$shell = get_template_directory() . '/pages/about.html';
	if ( ! is_file( $frag ) || ! is_file( $shell ) ) {
		return '';
	}
	$f = (string) file_get_contents( $frag );
	$s = (string) file_get_contents( $shell );
	if ( ! preg_match( '#<!--HEAD-->(.*?)<!--/HEAD-->#s', $f, $h ) || ! preg_match( '#<!--MAIN-->(.*?)<!--/MAIN-->#s', $f, $m ) ) {
		return '';
	}
	foreach ( array(
		'#<title[^>]*>.*?</title>\s*#is', '#<meta\s+name="description"[^>]*>\s*#i', '#<meta\s+name="author"[^>]*>\s*#i',
		'#<link\s+rel="canonical"[^>]*>\s*#i', '#<link\s+rel="alternate"\s+hreflang[^>]*>\s*#i',
		'#<meta\s+property="(?:og|article):[^"]*"[^>]*>\s*#i', '#<meta\s+name="twitter:[^"]*"[^>]*>\s*#i',
		'#<script\s+type="application/ld\+json"[^>]*>.*?</script>\s*#is',
	) as $rx ) {
		$s = preg_replace( $rx, '', $s );
	}
	$s = preg_replace( '#<meta\s+name="robots"[^>]*>#i', '<meta name="robots" content="noindex, follow">', $s, 1 );
	$s = preg_replace( '#(class="ucnav-t)\s+on"#', '$1"', $s ); // the shell page's "current page" highlight
	$s = preg_replace( '#(<a class="ucnav-t[^"]*"[^>]*?)\s+aria-current="page"#', '$1', $s );
	$i = strpos( $s, '</head>' );
	if ( false === $i ) {
		return '';
	}
	$s = substr( $s, 0, $i ) . $h[1] . substr( $s, $i );
	return (string) preg_replace_callback( '#<main\b.*?</main>#is', function () use ( $m ) {
		return $m[1];
	}, $s, 1 );
}

function ucan_serve_error_page( $code = 404 ) {
	$path = (string) wp_parse_url( isset( $_SERVER['REQUEST_URI'] ) ? (string) $_SERVER['REQUEST_URI'] : '/', PHP_URL_PATH );
	$html = ucan_error_template();

	if ( '' === $html ) { // template files missing: still answer honestly
		status_header( $code );
		header( 'Content-Type: text/html; charset=UTF-8' );
		echo '<!doctype html><meta charset="utf-8"><meta name="robots" content="noindex"><title>Not found</title><p>Page not found. <a href="/">U-CAN home</a>.</p>';
		exit;
	}
	$swap = function ( $tag, $text ) use ( &$html ) {
		$html = preg_replace_callback( '#<!--' . $tag . '-->.*?<!--/' . $tag . '-->#s', function () use ( $text ) {
			return $text;
		}, $html );
	};
	if ( 410 === $code ) {
		$swap( 'ERR-CODE', 'Error 410' );
		$swap( 'ERR-TITLE', 'This page has been removed' );
		$swap( 'ERR-MSG', 'This page was removed on purpose and is not coming back. The pages below are the best places to continue.' );
		$html = str_replace( 'Page not found | U-CAN', 'Page removed | U-CAN', $html );
	} else {
		$sugg = ucan_suggest_pages( $path );
		if ( $sugg ) {
			$li = '';
			foreach ( $sugg as $slug => $title ) {
				$li .= '<li><a href="/' . esc_attr( $slug ) . '">' . esc_html( $title ) . '</a></li>';
			}
			$swap( 'SUGGEST', '<div class="e404-sugg"><p>Did you mean:</p><ul>' . $li . '</ul></div>' );
		}
		ucan_log_404( $path );
	}
	$html = ucan_fill_placeholders( $html );

	status_header( $code );
	header( 'Content-Type: text/html; charset=UTF-8' );
	header( 'X-Robots-Tag: noindex, follow' );
	header( 'Cache-Control: public, max-age=300' );
	if ( function_exists( 'ucan_security_headers' ) ) {
		ucan_security_headers();
	}
	echo $html; // phpcs:ignore WordPress.Security.EscapeOutput -- theme-bundled page; dynamic parts escaped above.
	exit;
}

/* ------------------------------------------------------------- 404 log */

function ucan_log_404( $path ) {
	$method = isset( $_SERVER['REQUEST_METHOD'] ) ? strtoupper( (string) $_SERVER['REQUEST_METHOD'] ) : 'GET';
	if ( ! in_array( $method, array( 'GET', 'HEAD' ), true ) ) {
		return;
	}
	$p = substr( strtolower( '/' . trim( (string) $path, '/' ) ), 0, 200 );
	// vulnerability scanners probing for files: noise, not broken links
	if ( preg_match( '#(\.(php|env|sql|bak|zip|tar|gz|git|ini|log)\b|wp-(admin|includes|login|config)|xmlrpc|phpmyadmin|cgi-bin|\.\./)#i', $p ) ) {
		return;
	}
	$log = get_option( 'ucan_404_log', array() );
	$log = is_array( $log ) ? $log : array();
	$ref = '';
	if ( ! empty( $_SERVER['HTTP_REFERER'] ) ) {
		$h   = wp_parse_url( (string) $_SERVER['HTTP_REFERER'], PHP_URL_HOST );
		$ref = is_string( $h ) ? substr( $h, 0, 80 ) : ''; // host only: no personal data, no full URLs
	}
	if ( isset( $log[ $p ] ) ) {
		++$log[ $p ]['n'];
		$log[ $p ]['t'] = time();
		if ( $ref && empty( $log[ $p ]['r'] ) ) {
			$log[ $p ]['r'] = $ref;
		}
	} elseif ( count( $log ) < 300 ) {
		$log[ $p ] = array( 'n' => 1, 't' => time(), 'r' => $ref );
	} else {
		return;
	}
	update_option( 'ucan_404_log', $log, false );
}

add_action(
	'admin_menu',
	function () {
		add_management_page( '404 log', '404 log', 'manage_options', 'ucan-404-log', 'ucan_404_log_page' );
	}
);

function ucan_404_log_page() {
	if ( ! current_user_can( 'manage_options' ) ) {
		return;
	}
	$log = get_option( 'ucan_404_log', array() );
	$log = is_array( $log ) ? $log : array();
	uasort( $log, function ( $a, $b ) {
		return $b['n'] <=> $a['n'];
	} );
	$clear = wp_nonce_url( admin_url( 'admin-post.php?action=ucan_404_clear' ), 'ucan_404_clear' );
	?>
	<div class="wrap">
		<h1>404 log</h1>
		<p>Addresses visitors or crawlers asked for that do not exist, most requested first (scanner probes for
		<code>.php</code>/<code>wp-admin</code> files are ignored). A URL that keeps appearing with an outside
		<em>referrer</em> is a broken link somewhere else and is worth a 301 redirect. Only the path, a count and the
		referring site's domain are stored: no IP addresses, no full referrer URLs.</p>
		<p><a class="button" href="<?php echo esc_url( $clear ); ?>" onclick="return confirm('Clear the whole log?');">Clear log</a></p>
		<table class="widefat striped">
			<thead><tr><th>Requested path</th><th>Times</th><th>Last seen</th><th>Referring site</th></tr></thead>
			<tbody>
			<?php if ( ! $log ) : ?>
				<tr><td colspan="4">No missing pages recorded yet.</td></tr>
			<?php endif; ?>
			<?php foreach ( array_slice( $log, 0, 300, true ) as $p => $row ) : ?>
				<tr>
					<td><code><?php echo esc_html( $p ); ?></code></td>
					<td><?php echo (int) $row['n']; ?></td>
					<td><?php echo esc_html( wp_date( 'j M Y, H:i', (int) $row['t'] ) ); ?></td>
					<td><?php echo esc_html( isset( $row['r'] ) ? $row['r'] : '' ); ?></td>
				</tr>
			<?php endforeach; ?>
			</tbody>
		</table>
	</div>
	<?php
}

add_action(
	'admin_post_ucan_404_clear',
	function () {
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_die( 'Not allowed.' );
		}
		check_admin_referer( 'ucan_404_clear' );
		delete_option( 'ucan_404_log' );
		wp_safe_redirect( admin_url( 'tools.php?page=ucan-404-log' ) );
		exit;
	}
);
